# Generated by Django 4.1.2 on 2022-11-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0002_categorydb_alter_admindatabase_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('Productname', models.CharField(blank=True, max_length=30, null=True)),
                ('Productprice_per_kg', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
