# Generated by Django 4.1.2 on 2022-11-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0003_productdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='name',
        ),
    ]
