# Generated by Django 4.1.2 on 2022-11-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0004_remove_productdb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Productname',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Productprice_per_kg',
            new_name='productprice_per_kg',
        ),
    ]
