# Generated by Django 4.1.2 on 2023-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gofreshweb', '0002_adcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('totalprice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
