# Generated by Django 4.1.2 on 2023-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gofreshweb', '0004_itemcart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='image',
        ),
    ]
